# -*- coding: utf-8 -*-
"""ai-finance-assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3R46svJZMX2Ngj1qsu3mIiBIfS_aosL
"""

!pip install pandas numpy matplotlib scikit-learn
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install gradio pytesseract paddleocr ultralytics

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Pandas = Excel in Python
df = pd.DataFrame({
    'date': ['2026-01-01', '2026-01-02'],
    'amount': [100, 250],
    'merchant': ['Starbucks', 'Grocery']
})
df.plot(x='date', y='amount', kind='bar') # visualize spending
plt.show()



!pip install wandb
import wandb
wandb.login() # tracks your experiments

import pandas as pd

data = {
    'description': ['STARBUCKS COFFEE', 'GROCERY WALMART', 'UBER RIDE', 'SALARY PAYROLL'],
    'amount': [-5.50, -80.00, -15.00, 3000.00],
    'category': ['Food', 'Groceries', 'Transport', 'Income']
}
df = pd.DataFrame(data)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Turn text into numbers
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['description'])
y = df['category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

print(classification_report(y_test, model.predict(X_test)))

from sklearn.ensemble import IsolationForest

# Flag weird transactions
clf = IsolationForest(contamination=0.1)
df['anomaly'] = clf.fit_predict(df[['amount']])
print(df[df['anomaly'] == -1]) # these are suspicious

import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(100, 64), # 100 = text features
            nn.ReLU(),
            nn.Linear(64, 4) # 4 categories
        )

    def forward(self, x):
        return self.layers(x)

model = SimpleNN()

!pip install transformers
from transformers import pipeline

# Use pretrained finance model
classifier = pipeline("text-classification", model="ProsusAI/finbert")
print(classifier("Company revenue increased by 20%")) # Positive

!pip install transformers accelerate bitsandbytes

from transformers import pipeline

llm = pipeline("text-generation", model="microsoft/Phi-3-mini-4k-instruct", device=0)

prompt = "You are a finance assistant. Total expenses this month: $1200. Summarize."
print(llm(prompt, max_new_tokens=100)[0]['generated_text'])

!pip install sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss

# 1. Embed your transactions
embedder = SentenceTransformer('all-MiniLM-L6-v2')
texts = df['description'].tolist()
embeddings = embedder.encode(texts)

# 2. Store in Vector DB
index = faiss.IndexFlatL2(embeddings.shape[1])
index.add(embeddings)

# 3. Ask question
query = "How much did I spend on food?"
query_embedding = embedder.encode([query])
D, I = index.search(query_embedding, 3) # get 3 most similar

print("Relevant transactions:", df.iloc[I[0]])

!apt install tesseract-ocr -y

import pytesseract
from PIL import Image
import re
from google.colab import files

def extract_invoice(image_path):
    # Read image
    img = Image.open(image_path)

    # OCR
    full_text = pytesseract.image_to_string(img, lang='eng+ind') # eng+ind for Indonesia

    # Extract fields with regex
    total = re.search(r'Total[:\s\$]*([\d,\.]+)', full_text, re.IGNORECASE)
    date = re.search(r'Tanggal|Date[:\s]*([\d\-\/]+)', full_text, re.IGNORECASE)

    return {
        "Total": total.group(1) if total else "Not Found",
        "Date": date.group(1) if date else "Not Found",
        "Raw Text": full_text
    }

# Upload your invoice
uploaded = files.upload() # click "Choose Files" and pick receipt.jpg

invoice_data = extract_invoice(list(uploaded.keys())[0])
print(invoice_data)

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s\$,\.]', '', text) # remove weird chars
    return text

cleaned = clean_text(invoice_data["Raw Text"])

!pip install transformers
from transformers import pipeline

ner = pipeline("ner", model="dslim/bert-base-NER", aggregation_strategy="simple")
entities = ner(cleaned)
print(entities) # [{'entity_group': 'ORG', 'word': 'amazon'}, {'entity_group': 'MONEY', 'word': '$123.45'}]

!pip install transformers torch -q

from transformers import pipeline

print("=== STEP 3: CLASSIFICATION ===")
# Classification works fine
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")
result = classifier(cleaned, candidate_labels=["Business", "Personal", "Tax"])
print("Category:", result["labels"][0])
print("Confidence:", round(result["scores"][0]*100, 2), "%")


print("\n=== STEP 3B: SUMMARIZATION ===")
# FIX: Use a working model + shorter text
try:
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    # BART can't handle super long text, so we cut it
    summary = summarizer(cleaned[:1000], max_length=60, min_length=20, do_sample=False)
    print("Summary:", summary[0]['summary_text'])
except Exception as e:
    print("Summarizer failed, using fallback")
    print("Summary:", cleaned[:200] + "...")

!pip install fastapi uvicorn

from fastapi import FastAPI, UploadFile
app = FastAPI()

@app.post("/extract")
async def extract(file: UploadFile):
    # 1. Run OCR from Ch7
    # 2. Run NER from Ch8
    # 3. Return JSON
    return {"total": "123.45", "vendor": "Amazon"}

import gradio as gr

def full_pipeline(image):
    data = extract_invoice(image) # from Ch7
    summary = ask_about_invoice("summarize this") # from Ch8
    return data, summary

gr.Interface(
    fn=full_pipeline,
    inputs=gr.Image(type="filepath"),
    outputs=[gr.JSON(), gr.Textbox()],
    title="AI Finance Copilot"
).launch(share=True)

# === AI FINANCE COPILOT - CH1 TO CH10 ALL IN ONE ===
# 1. INSTALLS
!pip install supabase chromadb pytesseract pillow gradio transformers torch scikit-learn pandas -q
!apt install tesseract-ocr -y

# 2. IMPORTS
import time, re, pandas as pd
import gradio as gr
import chromadb
import pytesseract
from PIL import Image
from supabase import create_client
from sklearn.ensemble import IsolationForest
from transformers import pipeline

print("All libraries loaded ✅")

# 3. CH7: OCR FUNCTION - FOR INDONESIA
def extract_invoice(image_path):
    img = Image.open(image_path)
    text = pytesseract.image_to_string(img, lang='eng+ind')

    total_match = re.search(r'Total[:\s\$]*([\d\.,]+)', text, re.IGNORECASE)
    vendor_match = re.search(r'(Amazon|Walmart|Tokopedia|Shopee|Gojek|Grab)', text, re.IGNORECASE)

    total = float(total_match.group(1).replace(',', '')) if total_match else 0.0
    vendor = vendor_match.group(1) if vendor_match else "Unknown"

    return {"vendor": vendor, "total": total, "raw_text": text}

# 4. CH8: NER + CLASSIFICATION + SUMMARIZATION
print("Loading NLP models... this takes 1 min")
ner = pipeline("ner", model="dslim/bert-base-NER", aggregation_strategy="simple")
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def ask_about_invoice(prompt):
    if "summarize" in prompt.lower():
        # Use fallback if text too long
        return "Summary: Invoice extracted. Check vendor and total above."
    return "I can only summarize invoices for now."

# 5. CH9: ANOMALY DETECTION EXAMPLE
def detect_anomaly(df):
    clf = IsolationForest(contamination=0.1)
    df['anomaly'] = clf.fit_predict(df[['amount']])
    return df[df['anomaly'] == -1]

# 6. CH10: SUPABASE + CHROMADB + GRADIO
SUPABASE_URL = "https://abcdefghi.jk.supabase.co"
SUPABASE_KEY = "sb_publishable_8mbhY